name: Deploy prod strapi admin on push master

on:
  push:
    branches:
      - master

jobs:
  web-deploy:

    name: Deploy strapi admin
    runs-on: ubuntu-latest

    env:
      SERVER: admin.tmmk.in

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 18 LTS
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.SERVER }}
        username: ${{ secrets.ftp_username}}
        password: ${{ secrets.ftp_password }}
        server-dir: /
        local-dir: ./dist/
        #dangerous-clean-slate: true
